export interface User {
  id: number;
  firstName: string;
  email: string;
  profilePhoto?: string; // Base64 encoded image
  password: string; // Simple hash for demo purposes
}

export interface TimeEntry {
  id: number;
  userId: number;
  date: string; // "2025-11-11"
  clockIn: string; // ISO timestamp
  clockOut: string | null;
  lunchBreakStart: string | null;
  lunchBreakEnd: string | null;
  shortBreaks: Array<{ start: string; end: string | null }>;
  totalHours: number | null;
  status: "clocked_in" | "on_lunch" | "on_break" | "clocked_out" | "auto_closed";
  isLate: boolean;
  notes: string;
}

export interface LeaveRequest {
  id: number;
  userId: number;
  leaveType: "annual" | "sick";
  startDate: string;
  endDate: string;
  isHalfDay: boolean;
  daysRequested: number;
  reason: string;
  status: "pending" | "approved" | "denied" | "auto_approved";
  approvedBy: number | null;
}

export interface SalaryRecord {
  id: string;
  employeeId: number;
  employeeName: string;
  amount: number;
  currency: string;
  paymentMonth: string;
  workPeriodStart: string;
  workPeriodEnd: string;
  status: 'pending' | 'paid' | 'overdue';
  paidDate: string | null;
  paidBy: number | null;
  autoGenerated: boolean;
  generatedDate: string;
  dueDate: string;
  reminderSent: boolean;
  employeeNotified: boolean;
  createdAt: string;
  updatedAt: string;
}

// Type alias for backward compatibility
export type SalaryPayment = SalaryRecord;

export interface Notification {
  id: number;
  userId: number;
  type: "leave_submitted" | "leave_approved" | "leave_denied" | "salary_paid" | "salary_confirmed" | "sick_leave" | "salary" | "salary_reminder";
  title: string;
  message: string;
  isRead: boolean;
  createdAt: string;
  relatedId?: number;
  relatedType?: "leave" | "salary";
}